Done

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -114,56 +114,6 @@ check_disk_and_memory() {
 }
 
 ##
-## standard http / https ports must not be occupied
-##
-check_ports() {
-    check_port "80"
-    check_port "443"
-    echo "Ports 80 and 443 are free for use"
-}
-
-
-##
-## check a port to see if it is already in use
-##
-check_port() {
-
-  local valid=$(netstat -tln | awk '{print $4}' | grep ":${1}\$")
-
-  if [ -n "$valid" ]; then
-    echo "Port ${1} appears to already be in use."
-    echo
-    echo "This will show you what command is using port ${1}"
-    lsof -i tcp:${1} -s tcp:listen
-    echo
-    echo "If you are trying to run GeoSpark simultaneously with another web"
-    echo "server like Apache or nginx, you will need to bind to a different port"
-    echo
-    echo "If you are reconfiguring an already-configured GeoSpark, use "
-    echo
-    echo "./launcher stop app"
-    echo
-    echo "to stop GeoSpark before you reconfigure it and try again."
-    exit 1
-  fi
-}
-
-##
-## read a variable from the config file
-##
-read_config() {
-  config_line=`egrep "^  #?$1:" $web_file`
-  read_config_result=`echo $config_line | awk  -F":" '{print $2}'`
-  read_config_result=`echo $read_config_result | sed "s/^\([\"']\)\(.*\)\1\$/\2/g"`
-}
-
-read_default() {
-  config_line=`egrep "^  #?$1:" samples/standalone.yml`
-  read_default_result=`echo $config_line | awk  -F":" '{print $2}'`
-  read_default_result=`echo $read_config_result | sed "s/^\([\"']\)\(.*\)\1\$/\2/g"`
-}
-
-##
 ## If we have lots of RAM or lots of CPUs, bump up the defaults to scale better
 ##
 scale_ram_and_cpu() {
@@ -220,6 +170,408 @@ scale_ram_and_cpu() {
   fi
 
   echo $data_file memory parameters updated.
+}
+
+##
+## standard http / https ports must not be occupied
+##
+check_ports() {
+    check_port "80"
+    check_port "443"
+    echo "Ports 80 and 443 are free for use"
+}
+
+
+##
+## check a port to see if it is already in use
+##
+check_port() {
+
+  local valid=$(netstat -tln | awk '{print $4}' | grep ":${1}\$")
+
+  if [ -n "$valid" ]; then
+    echo "Port ${1} appears to already be in use."
+    echo
+    echo "This will show you what command is using port ${1}"
+    lsof -i tcp:${1} -s tcp:listen
+    echo
+    echo "If you are trying to run GeoSpark simultaneously with another web"
+    echo "server like Apache or nginx, you will need to bind to a different port"
+    echo
+    echo "If you are reconfiguring an already-configured GeoSpark, use "
+    echo
+    echo "./launcher stop app"
+    echo
+    echo "to stop GeoSpark before you reconfigure it and try again."
+    exit 1
+  fi
+}
+
+##
+## read a variable from the config file
+##
+read_config() {
+  config_line=`egrep "^  #?$1:" $web_file`
+  read_config_result=`echo $config_line | awk  -F":" '{print $2}'`
+  read_config_result=`echo $read_config_result | sed "s/^\([\"']\)\(.*\)\1\$/\2/g"`
+}
+
+read_default() {
+  config_line=`egrep "^  #?$1:" samples/standalone.yml`
+  read_default_result=`echo $config_line | awk  -F":" '{print $2}'`
+  read_default_result=`echo $read_config_result | sed "s/^\([\"']\)\(.*\)\1\$/\2/g"`
+}
+
+##
+## prompt user for typical GeoSpark config file values
+##
+ask_user_for_config() {
+
+  # NOTE: Defaults now come from standalone.yml
+
+  local changelog=/tmp/changelog.$PPID
+  read_config "GEOSPARK_SMTP_ADDRESS"
+  local smtp_address=$read_config_result
+  # NOTE: if there are spaces between emails, this breaks, but a human should be paying attention
+  read_config "GEOSPARK_DEVELOPER_EMAILS"
+  local developer_emails=$read_config_result
+  read_config "GEOSPARK_SMTP_PASSWORD"
+  local smtp_password=$read_config_result
+  read_config "GEOSPARK_SMTP_PORT"
+  local smtp_port=$read_config_result
+  read_config "GEOSPARK_SMTP_USER_NAME"
+  local smtp_user_name=$read_config_result
+  if [ "$smtp_password" = "pa$$word" ]
+  then
+      smtp_password = ""
+  fi
+  read_config "LETSENCRYPT_ACCOUNT_EMAIL"
+  local letsencrypt_account_email=$read_config_result
+  if [ -z $letsencrypt_account_email ]
+  then
+      letsencrypt_account_email="me@example.com"
+  fi
+  if [ "$letsencrypt_account_email" = "me@example.com" ]
+  then
+      local letsencrypt_status="ENTER to skip"
+  else
+    local letsencrypt_status="Enter 'OFF' to disable."
+  fi
+
+  read_config "GEOSPARK_HOSTNAME"
+  hostname=$read_config_result
+
+  local new_value=""
+  local config_ok="n"
+  local update_ok="y"
+
+  echo ""
+
+  while [[ "$config_ok" == "n" ]]
+  do
+    if [ ! -z "$hostname" ]
+    then
+      read -p "Hostname for your GeoSpark? [$hostname]: " new_value
+      if [ ! -z "$new_value" ]
+      then
+          hostname="$new_value"
+      fi
+      if [[ $hostname =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
+      then
+        echo
+        echo "GeoSpark requires a DNS hostname. IP addresses are unsupported and will not work."
+        echo
+        hostname="geospark-api.example.com"
+      fi
+    fi
+
+    if [ ! -z "$developer_emails" ]
+    then
+      read -p "Email address for admin account(s)? [$developer_emails]: " new_value
+      if [ ! -z "$new_value" ]
+      then
+          developer_emails="$new_value"
+      fi
+    fi
+
+    if [ ! -z "$smtp_address" ]
+    then
+      read -p "SMTP server address? [$smtp_address]: " new_value
+      if [ ! -z "$new_value" ]
+      then
+        smtp_address="$new_value"
+      fi
+    fi
+
+    if [ ! -z "$smtp_port" ]
+    then
+      read -p "SMTP port? [$smtp_port]: " new_value
+      if [ ! -z "$new_value" ]
+      then
+        smtp_port="$new_value"
+      fi
+    fi
+
+    ##
+    ## automatically set correct user name based on common mail providers unless it's been set
+    ##
+    if [ "$smtp_user_name" == "user@example.com" ]
+    then
+      if [ "$smtp_address" == "smtp.sparkpostmail.com" ]
+      then
+        smtp_user_name="SMTP_Injection"
+      fi
+      if [ "$smtp_address" == "smtp.sendgrid.net" ]
+      then
+        smtp_user_name="apikey"
+      fi
+      if [ "$smtp_address" == "smtp.mailgun.org" ]
+      then
+        smtp_user_name="postmaster@$hostname"
+      fi
+    fi
+
+    if [ ! -z "$smtp_user_name" ]
+    then
+      read -p "SMTP user name? [$smtp_user_name]: " new_value
+      if [ ! -z "$new_value" ]
+      then
+          smtp_user_name="$new_value"
+      fi
+    fi
+
+    read -p "SMTP password? [$smtp_password]: " new_value
+    if [ ! -z "$new_value" ]
+    then
+        smtp_password="$new_value"
+    fi
+
+    if [ ! -z $letsencrypt_account_email ]
+    then
+      read -p "Optional email address for setting up Let's Encrypt? ($letsencrypt_status) [$letsencrypt_account_email]: " new_value
+      if [ ! -z "$new_value" ]
+      then
+          letsencrypt_account_email="$new_value"
+          if [ "${new_value,,}" = "off" ]
+          then
+            letsencrypt_status="ENTER to skip"
+          else
+            letsencrypt_status="Enter 'OFF' to disable."
+          fi
+      fi
+    fi
+
+    if [ "$letsencrypt_status" == "Enter 'OFF' to disable." ]
+    then
+       check_IP_match $hostname
+    fi
+
+    echo -e "\nDoes this look right?\n"
+    echo "Hostname      : $hostname"
+    echo "Email         : $developer_emails"
+    echo "SMTP address  : $smtp_address"
+    echo "SMTP port     : $smtp_port"
+    echo "SMTP username : $smtp_user_name"
+    echo "SMTP password : $smtp_password"
+
+    if [ "$letsencrypt_status" == "Enter 'OFF' to disable." ]
+    then
+      echo "Let's Encrypt : $letsencrypt_account_email"
+    fi
+
+
+    echo ""
+    read -p "ENTER to continue, 'n' to try again, Ctrl+C to exit: " config_ok
+  done
+
+  sed -i -e "s/^  GEOSPARK_HOSTNAME:.*/  GEOSPARK_HOSTNAME: $hostname/w $changelog" $web_file
+  if [ -s $changelog ]
+  then
+    rm $changelog
+  else
+    echo "GEOSPARK_HOSTNAME change failed."
+    update_ok="n"
+  fi
+
+  sed -i -e "s/^  GEOSPARK_DEVELOPER_EMAILS:.*/  GEOSPARK_DEVELOPER_EMAILS: \'$developer_emails\'/w $changelog" $web_file
+  if [ -s $changelog ]
+  then
+    rm $changelog
+  else
+    echo "GEOSPARK_DEVELOPER_EMAILS change failed."
+    update_ok="n"
+  fi
+
+  sed -i -e "s/^  GEOSPARK_SMTP_ADDRESS:.*/  GEOSPARK_SMTP_ADDRESS: $smtp_address/w $changelog" $web_file
+  if [ -s $changelog ]
+  then
+    rm $changelog
+  else
+    echo "GEOSPARK_SMTP_ADDRESS change failed."
+    update_ok="n"
+  fi
+
+  sed -i -e "s/^  #\?GEOSPARK_SMTP_PORT:.*/  GEOSPARK_SMTP_PORT: $smtp_port/w $changelog" $web_file
+  if [ -s $changelog ]
+  then
+    rm $changelog
+  else
+    echo "GEOSPARK_SMTP_PORT change failed."
+    update_ok="n"
+  fi
+
+  sed -i -e "s/^  #\?GEOSPARK_SMTP_USER_NAME:.*/  GEOSPARK_SMTP_USER_NAME: $smtp_user_name/w $changelog" $web_file
+  if [ -s $changelog ]
+  then
+    rm $changelog
+  else
+    echo "GEOSPARK_SMTP_USER_NAME change failed."
+    update_ok="n"
+  fi
+
+  if [[ "$smtp_password" == *"\""* ]]
+  then
+    SLASH="BROKEN"
+    echo "========================================"
+    echo "WARNING!!!"
+    echo "Your password contains a quote (\")"
+    echo "Your SMTP Password will not be set. You will need to edit app.yml to enter it."
+    echo "========================================"
+    update_ok="n"
+  else
+    SLASH="|"
+    if [[ "$smtp_password" == *"$SLASH"* ]]
+    then SLASH="+"
+      if [[ "$smtp_password" == *"$SLASH"* ]]
+      then
+        SLASH="Q"
+        if [[ "$smtp_password" == *"$SLASH"* ]]
+  then
+    SLASH="BROKEN"
+          echo "========================================"
+          echo "WARNING!!!"
+          echo "Your password contains all available delimiters (+, |, and Q). "
+          echo "Your SMTP Password will not be set. You will need to edit app.yml to enter it."
+          echo "========================================"
+          update_ok="n"
+         fi
+       fi
+    fi
+  fi
+  if [[ "$SLASH" != "BROKEN" ]]
+  then
+    sed -i -e "s${SLASH}^  #\?GEOSPARK_SMTP_PASSWORD:.*${SLASH}  GEOSPARK_SMTP_PASSWORD: \"${smtp_password}\"${SLASH}w $changelog" $web_file
+
+    if [ -s $changelog ]
+    then
+      rm $changelog
+    else
+      echo "GEOSPARK_SMTP_PASSWORD change failed."
+      update_ok="n"
+    fi
+  fi
+  if [ "$letsencrypt_status" = "ENTER to skip" ]
+  then
+      local src='^  #\?- "templates\/web.ssl.template.yml"'
+      local dst='  #\- "templates\/web.ssl.template.yml"'
+      sed -i -e "s/$src/$dst/w $changelog" $web_file
+      if [ ! -s $changelog ]
+      then
+        update_ok="n"
+        echo "web.ssl.template.yml NOT DISABLED--Are you using a non-standard template?"
+      fi
+      local src='^  #\?- "templates\/web.letsencrypt.ssl.template.yml"'
+      local dst='  #- "templates\/web.letsencrypt.ssl.template.yml"'
+
+      sed -i -e "s/$src/$dst/w $changelog" $web_file
+      if [ ! -s $changelog ]
+      then
+        update_ok="n"
+        echo "web.ssl.template.yml NOT DISABLED--Are you using a non-standard template?"
+      fi
+  else # enable let's encrypt
+    echo "Let's Encrypt will be enabled for $letsencrypt_account_email"
+      sed -i -e "s/^  #\?LETSENCRYPT_ACCOUNT_EMAIL:.*/  LETSENCRYPT_ACCOUNT_EMAIL: $letsencrypt_account_email/w $changelog" $web_file
+      if [ -s $changelog ]
+      then
+        rm $changelog
+      else
+        echo "LETSENCRYPT_ACCOUNT_EMAIL change failed."
+        update_ok="n"
+      fi
+      local src='^  #\?- "templates\/web.ssl.template.yml"'
+      local dst='  \- "templates\/web.ssl.template.yml"'
+      sed -i -e "s/$src/$dst/w $changelog" $web_file
+      if [ -s $changelog ]
+      then
+    echo "web.ssl.template.yml enabled"
+      else
+        update_ok="n"
+        echo "web.ssl.template.yml NOT ENABLED--was it on already?"
+      fi
+      local src='^  #\?- "templates\/web.letsencrypt.ssl.template.yml"'
+      local dst='  - "templates\/web.letsencrypt.ssl.template.yml"'
+
+      sed -i -e "s/$src/$dst/w $changelog" $web_file
+      if [ -s $changelog ]
+      then
+        echo "letsencrypt.ssl.template.yml enabled"
+      else
+        update_ok="n"
+        echo "letsencrypt.ssl.template.yml NOT ENABLED -- was it on already?"
+      fi
+  fi
+
+  if [ "$update_ok" == "y" ]
+  then
+    echo -e "\nConfiguration file at $config_file updated successfully!\n"
+  else
+    echo -e "\nUnfortunately, there was an error changing $config_file\n"
+    echo -d "This may happen if you have made unexpected changes."
+    exit 1
+  fi
+}
+
+##
+## is our config file valid? Does it have the required fields set?
+##
+validate_config() {
+
+  valid_config="y"
+
+  for x in GEOSPARK_SMTP_ADDRESS GEOSPARK_SMTP_USER_NAME GEOSPARK_SMTP_PASSWORD \
+           GEOSPARK_DEVELOPER_EMAILS GEOSPARK_HOSTNAME
+  do
+    read_config $x
+    local result=$read_config_result
+    read_default $x
+    local default=$read_default_result
+
+    if [ ! -z "$result" ]
+    then
+      if [[ "$config_line" = *"$default"* ]]
+      then
+        echo "$x left at incorrect default of $default"
+        valid_config="n"
+      fi
+      config_val=`echo $config_line | awk '{print $2}'`
+      if [ -z $config_val ]
+      then
+        echo "$x was not configured"
+        valid_config="n"
+      fi
+    else
+      echo "$x not present"
+      valid_config="n"
+    fi
+  done
+
+  if [ "$valid_config" != "y" ]; then
+    echo -e "\nSorry, these $web_file settings aren't valid -- can't continue!"
+    echo "If you have unusual requirements, edit $web_file and then: "
+    echo "./launcher bootstrap $app_name"
+    exit 1
+  fi
 }
 
 ##
@@ -297,3 +649,22 @@ else
 fi
 
 scale_ram_and_cpu
+ask_user_for_config
+validate_config
+
+##
+## if we reach this point without exiting, OK to proceed
+## rebuild won't fail if there's nothing to rebuild and does the restart
+##
+echo "Updates successful. Rebuilding in 5 seconds."
+sleep 5 # Just a chance to ^C in case they were too fast on the draw
+if [ "$data_name" == "$app_name" ]
+then
+    echo Building $app_name
+    ./launcher rebuild $app_name
+else
+    echo Building $data_name now . . .
+    ./launcher rebuild $data_name
+    echo Building $app_name now . . .
+    ./launcher rebuild $app_name
+fi
